// File generated by FlutterFire CLI.
// ignoring_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtDSqUmXgko2b9wn6aLnd6DjsLL3TiLeg',
    appId: '1:492570746016:android:849c6d5e49a0972dedbdc5',
    messagingSenderId: '492570746016',
    projectId: 'blinkiefash-18d9f',
    storageBucket: 'blinkiefash-18d9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtDSqUmXgko2b9wn6aLnd6DjsLL3TiLeg',
    appId: '1:492570746016:ios:849c6d5e49a0972dedbdc5',
    messagingSenderId: '492570746016',
    projectId: 'blinkiefash-18d9f',
    storageBucket: 'blinkiefash-18d9f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtDSqUmXgko2b9wn6aLnd6DjsLL3TiLeg',
    appId: '1:492570746016:ios:849c6d5e49a0972dedbdc5',
    messagingSenderId: '492570746016',
    projectId: 'blinkiefash-18d9f',
    storageBucket: 'blinkiefash-18d9f.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtDSqUmXgko2b9wn6aLnd6DjsLL3TiLeg',
    appId: '1:492570746016:web:849c6d5e49a0972dedbdc5',
    messagingSenderId: '492570746016',
    projectId: 'blinkiefash-18d9f',
    storageBucket: 'blinkiefash-18d9f.firebasestorage.app',
  );
}
