android.newDsl=false
android.useAndroidX=true
android.enableJetifier=true
android.experimental.enableNewResourceShrinker=true
android.experimental.enableNewResourceShrinker.validatedR8=true
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g --enable-native-access=ALL-UNNAMED
org.gradle.warning.mode=none
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.java.home=/Users/sa40091223/.jdks/android-studio-jbr
android.builtInKotlin=false
